#!/usr/bin/env bash
# Display 'To infinity and beyond' infinitely with sleep 2 in each iteration of the loop, with some more conditions.

touch /var/run/myscript.pid
pgrep axuf | grep 'myscript' >/var/run/myscript.pid

trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid' SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
