#!/usr/bin/env bash
# Display 'To infinity and beyond' infinitely with sleep 2 in each iteration of the loop.

trap 'echo "I am invincible!!!"' SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
