#!/usr/bin/env bash
# print the phrase 'Best School' 10 times with some conditions
phrase="Best School"
i=0
while [ $i -lt 10 ]; do
    if [ $i -eq 3 ]; then
        echo "bad luck"
    elif [ $i -eq 7 ]; then
        echo "good luck"
    else
        echo "$phrase"
    fi
    i=$((i + 1))
done
