#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes

hour=0
minute=0

while [ $hour -lt 13 ]; do
    echo "Hour: $hour"
    while [ $minute -lt 60 ]; do
        echo "$minute"
        minute=$((minute + 1))
    done
    minute=0
    hour=$((hour + 1))
done
